### ISSUE TITLE
这个项目有企信的回调解密吗？

### ISSUE THREAD

**Issue by YSHIDM** [witjs/wecom#1]
修改客户信息等操作会向回调服务器发送请求，其中包含了加密信息，这个项目能解密吗？
官方提供的npm 包只能解密一部分，剩余的疑似请求信息有错

**Comment by witjs** [comment]
请提供一下对应的接口~或者是文档地址

**Comment by YSHIDM** [comment]
这个问题已经解决了，需要配置两个回调服务接口，一个是客户的，一个是应用的，
貌似每个接口都会收到所有的回调请求，需要根据 agentId 区分，使用各自的 token 和 aeskey 解密（可以设置成相同的）
