### ISSUE TITLE
请问请求时token过期会自动刷新token后重试吗

### ISSUE THREAD

**Issue by hovees** [witjs/wecom#2]

**Comment by witjs** [comment]
会的，retryTimes 默认为3。可以修改重试次数

**Comment by hovees** [comment]
> 会的，retryTimes 默认为3。可以修改重试次数

https://github.com/witjs/wecom/blob/master/src/wecom.ts#L91
token过期好像并不会进error, response code是200的，是不是需要更新一下通过errcode来判断才是对的

[企业微信全局错误代码](https://work.weixin.qq.com/api/doc/90000/90139/90313)
[接口测试](https://open.work.weixin.qq.com/wwopen/devtool/interface?doc_id=10019)

**Comment by hovees** [comment]
@witjs

**Comment by witjs** [comment]
多谢反馈
记得之前鉴权失败返回的是403状态码的
大意了

已修改
请升级版本至`0.8.2`

**Comment by witjs** [comment]
这个issue我就先关了
如果发现还有问题的话
欢迎反馈
